version: '3'

services:
  reverseproxy:
    image: nginx:stable-alpine
    volumes:
      - ./reverseproxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/data:ro
      - ./viewer:/viewer:ro
      - ./website:/website:ro
      - ./log:/var/log/nginx/
    ports:
      - 127.0.0.1:8000:80
    restart: always

  database:
    image: mdillon/postgis:10-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./database/postgres.env
    restart: always

  terrain:
    image: geodata/cesium-terrain-server
    volumes:
      - ./data/terrain:/data/terrain:ro
    command: ['cesium-terrain-server', '-dir', '/data/terrain']
    depends_on:
      - reverseproxy
    restart: always

  api:
    build: ./seslr-api
    environment:
      - SESLR_APP_MODE=prod
    env_file:
      - ./database/postgres.env
    depends_on:
      - reverseproxy
      - database
    restart: always

  tms:
    image: nginx:stable-alpine
    volumes:
      - ./data/tms:/data:ro
      - ./tms/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

  viewer:
    build: ./viewer
    depends_on:
      - api
      - tms
      - terrain
    restart: always
